### ISSUE TITLE
Publish a blog post about k6-browser internals

### ISSUE THREAD

**Issue by inancgumus** [grafana/k6-docs#1428]
```[tasklist]
### Tasks
- [ ] [Finish the internal documentation updates](https://github.com/grafana/k6-internal-docs/issues/341) (_50% is done_)
- [ ] Kick off the process of turning our internal content into blog posts
- [ ] Ask the k6-browser team for proof-read
- [ ] Work with the content team to have the public post(s) published
```
